camel.main.name=delivery-service

camel.server.enabled=true

camel.component.amqp.connectionFactory=#class:org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory
camel.component.amqp.connectionFactory.brokerURL={{env:ARTEMIS_AMQP_URL}}
camel.component.amqp.username={{env:ARTEMIS_USER}}
camel.component.amqp.password={{env:ARTEMIS_PASSWORD}}